### ISSUE TITLE
import from vision

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/speech#1]
import from vision

**Comment by jgvictores** [comment]
Work in progress in `develop`, up to ff17933c53b49b2b146ed22e76ba25820afa21db for now.

**Comment by jgvictores** [comment]
All imported as of 7b9e744035ca374402b866fc1219e89801fc8f95.

In fact, all working except for #2 which was already broken on teo-head=vision ever since https://github.com/roboticslab-uc3m/vision/issues/53 (shared libraries).

**Comment by rsantos88** [comment]
So, it's important not to update the old `teo-head` repository to `vision` on **teo-head PC** until it's finally solved issue #2

**Comment by jgvictores** [comment]
@rsantos88 As commented, both `vision` and `speech` are fine for use with the demos. Thanks!
