### ISSUE TITLE
[speechRecognition] change protocol from strings to vocabs?

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/speech#20]
[speechRecognition] change protocol from strings to vocabs?

Impacts on repos:
- https://github.com/roboticslab-uc3m/follow-me

**Comment by PeterBowman** [comment]
I don't think this is doable. If you take a look into the generated IDL .cpp, the command name in the `read` callback is interpreted as a string tag (see [WireReader.cpp](https://github.com/robotology/yarp/blob/ca4de800bb877d158af9f782c77202f735024aa6/src/libYARP_os/src/yarp/os/idl/WireReader.cpp#L548-L583)). I believe the whole point of YARP/IDL is to avoid manually crafting a server/client interface, which would involve low-level vocab definitions.
