### ISSUE TITLE
[Espeak] `say(const std::string& text)`: is/can it be blocking?

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/speech#21]
[Espeak] `say(const std::string& text)`: is/can it be blocking?

Is it streaming as before or can it now be used as an RPC service?

If so, hard-coded waits such as the following can be refactored: https://github.com/roboticslab-uc3m/follow-me/blob/b462dad42fc243732744ccb276249a341ce9c2d3/programs/followMeDialogueManager/StateMachine.cpp#L131

**Comment by jgvictores** [comment]
The server is implemented as RPC, so something could be done here, and I believe it should.

I think we have two options here:
1. Make it blocking. Advantage: No change in API. Disadvantage: We loose flexibility.
1. Create new function like `checkSayDone`. Advantage: We maintain and even gain flexibility. Disadvantage: Change in API, and small sync issues similar to those in controlboard.

I like the last option a bit more, but I'm open to opinions.

**Comment by PeterBowman** [comment]
I'd advise against the first option. In the future, if not yet, you might want to implement a `stopTalking` (or `shutUp` 😀) method, which I believe would come up against serious difficulties when going the blocking way, at least as I found out while working in a similar problem at kinematics-dynamics (https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/106). Going back to the kin-dyn repo, we introduced not so long ago a `wait` method which might be of use here ([prototype](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/f3f6f880430c3eb58318b3e860315b8bd70113bc/libraries/YarpPlugins/ICartesianControl.h#L258-L269)) and would count as a 2b option. That would require the least work downstream, just replace current hardcoded waits with this new interface method.

**Comment by PeterBowman** [comment]
> No, it's not blocking but it's good to have a bit delay before muting

Sorry, but this statement is **false**, the `say` command does block ([here](https://github.com/roboticslab-uc3m/speech/blob/7694c9ae9919d977d31b7a76d40060135b9aea37/libraries/YarpPlugins/Espeak/Espeak.cpp#L117))...

**Comment by PeterBowman** [comment]
And it makes no sense to block since we provide [pause/resume/stop commands](https://github.com/roboticslab-uc3m/speech/blob/7694c9ae9919d977d31b7a76d40060135b9aea37/libraries/YarpPlugins/Espeak/speech.thrift#L56-L69). So I guess it should be unblocked, and a new `wait` command be added?

**Comment by jgvictores** [comment]
> So I guess it should be unblocked

For sure.

> and a new `wait` command be added?

Seems like the quick and fast solution.

Note that the `checkSayDone` alternative proposed above was in analogy with `IPositionControl::checkMotionDone`.
- Pro (I think): Easier to `stop()` before termination without using threads in API-user-land.
- Cons: From https://stackoverflow.com/questions/50062009/how-to-find-if-espeak-ended-the-speech espeak looks event-based, so we'd have to keep the state modified by events we catch via callback. Additionally, usually `IPositionControl::checkMotionDone` rolls out to be an ugly loop.

No strong opinions in a `wait` vs `checkSayDone`, but perhaps food for thought. ^^

**Comment by PeterBowman** [comment]
Another point: `checkSayDone` would allow multi-user scenarios thanks to not having to block RPC comms on the server side.
