### ISSUE TITLE
speech-instructions.md are coupled

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/speech#22]
https://github.com/roboticslab-uc3m/speech/blob/2ed13755d900721a139f300daf37ad185bc7fcf6/doc/speech-instructions.md should be moved into corresponding README files.

**Comment by rsantos88** [comment]
So, do you want to pass this instructions directly to https://github.com/roboticslab-uc3m/speech/blob/develop/README.md?

**Comment by jgvictores** [comment]
speechRecognition -> https://github.com/roboticslab-uc3m/speech/tree/develop/programs/speechRecognition/README.md

Espeak -> https://github.com/roboticslab-uc3m/speech/tree/develop/libraries/YarpPlugins/Espeak/README.md

**Comment by rsantos88** [comment]
bad links

**Comment by jgvictores** [comment]
Nope, files to be created. Links to the future.  : )

**Comment by rsantos88** [comment]
aha! ok ok

**Comment by rsantos88** [comment]
done https://github.com/roboticslab-uc3m/speech/pull/23

**Comment by jgvictores** [comment]
Cool, closing! Thanks!!
