### ISSUE TITLE
Implement Mimic 3 engine (TTS)

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/speech#30]
@rsantos88 has found a "fast, privacy-focused, open-source, neural Text to Speech (TTS) engine" that looks great:

https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-tts/mimic-3
https://github.com/MycroftAI/mimic3
https://github.com/MycroftAI/mimic3-voices

It is lightweight, offline, and features human-like voice (as opposed to the more robotic one we currently use via eSpeak). It is written in Python and can be installed through pip ([mycroft-mimic3-tts package](https://pypi.org/project/mycroft-mimic3-tts/)). There are four available Spanish voices (3 male, 1 female) compiled in two datasets; the "tux" voice from the "m-ailabs" dataset sounds quite appealing.

Sample invocation:

`mimic3 --voice es_ES/m-ailabs#tux "hola, me llamo teo y tengo 10 años"`

(or simply `--voice es_ES/m-ailabs` since `tux` is the default voice)

Pro tip: add `--cuda` to enable GPU acceleration (requires the "onnxruntime-gpu" pip package).

I'm thinking of a Python client implementation of our [TextToSpeech IDL service](https://github.com/roboticslab-uc3m/speech/blob/ee5a945b245deea9aea9c07d799627f7eb7f1f55/libraries/SpeechIDL/speech.thrift#L3-L66) similar to [speechRecognition.py](https://github.com/roboticslab-uc3m/speech/blob/ee5a945b245deea9aea9c07d799627f7eb7f1f55/programs/speechRecognition/speechRecognition.py).

**Comment by PeterBowman** [comment]
As a side note regarding installation: although the voice models should be automatically downloaded by the CLI app and stored in `${HOME}/.local/share/mycroft/mimic3/voices` on first use, in my case the process got stuck every time and I had to complete it manually. I provided the link to the mimic3-voices in the previous comment. Note that there is a *generator.onnx* inside each voice directory that is handled by Git LFS (which weighs around 60-70 MB). It needs to be downloaded and pasted in the correct location separately.

See also https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-tts/mimic-3#downloading-voices and the `mimic3-download` command.

**Comment by PeterBowman** [comment]
Already working (not fully implemented) at https://github.com/roboticslab-uc3m/speech/commit/7fadf45293a6b0233f8bc55de8878fcc601a2ba3.

@rsantos88 in case you want to use this in the upcoming demos, assuming you have installed the Spanish voices, launch it with:

`speechSynthesis --voice es_ES/m-ailabs --speaker tux`

On the teo-self-presentation side, pass `--language es_ES/m-ailabs#tux` to dialogueManager and change the output port in the yarpmanager's connections tab from "/teo/tts/rpc:s" to "/speechSynthesis/rpc:s".

**Comment by PeterBowman** [comment]
Done at https://github.com/roboticslab-uc3m/speech/commit/618cb83043737c2743c482f7d728d83eef756f2e. All IDL commands have been implemented except the pitch accessors, pause and resume. I'd consider expanding the API with volume commands and renaming "language" to "voice", which might or might not include speaker information.

There are two caveats to this implementation/engine:
1. On certain voices, including the Spanish ones, the last letters/vowels are trimmed from the synthesised result: https://github.com/MycroftAI/mimic3/issues/30 and https://github.com/MycroftAI/mimic3-voices/issues/4. It can be worked around for now by repeating the last letter, e.g. "holaa" instead of "hola".
2. MycroftAI has undergone staff reduction recently and seems to be on radio silence since the last [blog post](https://mycroft.ai/blog/update-from-the-ceo-part-1/) by their CEO back in January. For this reason, I'm forking their relevant repos into our org.

**Comment by synesthesiam** [comment]
Author of Mimic 3 here. I'm continuing my TTS work elsewhere: https://github.com/rhasspy/larynx2/

**Comment by PeterBowman** [comment]
> Author of Mimic 3 here. I'm continuing my TTS work elsewhere: https://github.com/rhasspy/larynx2/

Thank you for the heads-up and your great work! We have migrated from Mimic 3 to Piper (current name) at https://github.com/roboticslab-uc3m/speech/issues/33.
