### ISSUE TITLE
Think about gorinars/ros_voice_control

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/speech#4]
Think about https://github.com/gorinars/ros_voice_control
- uses [pocketsphinx-python](https://github.com/cmusphinx/pocketsphinx-python) **instead of Gstreamer**
- enables the keyword search mode, which should better filter not needed words
- is really simple (just a script to run)

**Comment by jgvictores** [comment]
Issue refers to current  [speechRecognition.py](https://github.com/roboticslab-uc3m/speech/blob/c319da5c21aa2bd7886133a9e5dc3b8bdf24c0d8/programs/speechRecognition/speechRecognition.py).

**Comment by PeterBowman** [comment]
We are happy with the current state of speechRecognition.py, see https://github.com/roboticslab-uc3m/speech/issues/8#issuecomment-968270204.
